frequency:  30 
sensor_timeout:  0.1
two_d_mode:  true
odom_frame:  $(arg prefix)odom
base_link_frame:  $(arg prefix)base_footprint
map_frame:  $(arg global_frame)
world_frame:  $(arg global_frame)

odom0: odometry/filtered_gpsodom
odom1: odometry/gps

odom0_differential:  true
odom0_relative:  false
odom1_differential:  true
odom1_relative:  false

# imu0_remove_gravitational_acceleration" type="bool:  true
print_diagnostics:  false